### ISSUE TITLE
Error during message sending

### ISSUE THREAD

**Issue by SPYNARY-Vodk** [isFakeAccount/psnawp#18]
Hi , during my test of your package an error occured when i have try to send private message : 

```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    user_online_id.send_private_message("Hello World!")
  File "/home/runner/psnawp/psnawp_api/user.py", line 134, in send_private_message
    self.group = group.Group(
  File "/home/runner/psnawp/psnawp_api/group.py", line 37, in __init__
    info = self.get_by_account_ids(account_ids)
  File "/home/runner/psnawp/psnawp_api/group.py", line 80, in get_by_account_ids
    response = self.request_builder.get(
  File "/home/runner/psnawp/psnawp_api/request_builder.py", line 39, in get
    response.raise_for_status()
  File "/home/runner/psnawp/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: `https://m.np.playstation.com/api/gamingLoungeGroups/v1/members/me/groups?includeFields=members%2CmainThread
```

did you know how fix it ? Have a good day 👍

**Comment by aron0306** [comment]
As stated in the comments right above the send_private_message function:
"Due to endpoint limitation. This will only work if the message group already exists."
So you have to create the message group manually (on the app, site etc) before being able to use this function.

**Comment by isFakeAccount** [comment]
https://github.com/isFakeAccount/psnawp/releases/tag/v1.0.0 fixed this issue.
